site_name: openVidu
site_url: https://openvidu.io/
site_description: A powerful platform to develop WebRTC real-time applications. Self-hosted, performant, fault tolerant, scalable and observable.
repo_name: openvidu/openvidu
repo_url: https://github.com/openvidu/openvidu

nav:
  - Home: index.md
  - OpenVidu Meet:
      - meet/index.md
      - Features:
          - Rooms and meetings: meet/features/rooms-and-meetings.md
          - Users and permissions: meet/features/users-and-permissions.md
          - Recordings: meet/features/recordings.md
          - Live Captions: meet/features/live-captions.md
          # - Transcriptions: meet-transcriptions.md
          # - Translations: meet-translations.md
          # - Summaries: meet-summaries.md
      - Deployment:
          - Try OpenVidu locally: meet/deployment/local.md # Describe the limitations about the basic deployment: lacks scalability and fault tolerance. Link to the OpenVidu Platform
          - Basic deployment: meet/deployment/basic.md
          - Advanced deployments: meet/deployment/advanced.md # Describe the limitations about the basic deployment: lacks scalability and fault tolerance. Link to the OpenVidu Platform
      - Embedded:
          - Introduction: meet/integrations/intro.md # Basic concepts...
          - Quickstart: meet/integrations/quickstart.md # Gettings started: step 1 (curl), step 2(embed html), ...
          - Tutorials:
              - meet/integrations/tutorials/index.md
              - JavaScript: meet/integrations/tutorials/javascript.md
          - Reference:
              - Webcomponent: meet/integrations/reference/webcomponent.md
              - REST API: meet/integrations/reference/rest.md
              - Webhooks: meet/integrations/reference/webhooks.md
  - OpenVidu Platform:
      - docs/index.md
      - Comparing OpenVidu: docs/comparing-openvidu.md
      - Developing your OpenVidu app:
          - docs/developing-your-openvidu-app/index.md
          - How to: docs/developing-your-openvidu-app/how-to.md
      - Tutorials:
          - Application Server:
              - docs/tutorials/application-server/index.md
              - Node.js: docs/tutorials/application-server/node.md
              - Go: docs/tutorials/application-server/go.md
              - Ruby: docs/tutorials/application-server/ruby.md
              - Java: docs/tutorials/application-server/java.md
              - Python: docs/tutorials/application-server/python.md
              - Rust: docs/tutorials/application-server/rust.md
              - PHP: docs/tutorials/application-server/php.md
              - .NET: docs/tutorials/application-server/dotnet.md
          - Application Client:
              - docs/tutorials/application-client/index.md
              - JavaScript: docs/tutorials/application-client/javascript.md
              - React: docs/tutorials/application-client/react.md
              - Angular: docs/tutorials/application-client/angular.md
              - Vue: docs/tutorials/application-client/vue.md
              - Electron: docs/tutorials/application-client/electron.md
              - Ionic: docs/tutorials/application-client/ionic.md
              - Android: docs/tutorials/application-client/android.md
              - iOS: docs/tutorials/application-client/ios.md
          - Advanced Features:
              - docs/tutorials/advanced-features/index.md
              - Recording Basic S3: docs/tutorials/advanced-features/recording-basic-s3.md
              - Recording Advanced S3: docs/tutorials/advanced-features/recording-advanced-s3.md
              - Recording Basic Azure: docs/tutorials/advanced-features/recording-basic-azure.md
              - Recording Advanced Azure: docs/tutorials/advanced-features/recording-advanced-azure.md
          - Angular Components:
              - docs/tutorials/angular-components/index.md
              - Custom UI: docs/tutorials/angular-components/openvidu-custom-ui.md
              - Custom Toolbar: docs/tutorials/angular-components/openvidu-custom-toolbar.md
              - Toolbar Buttons: docs/tutorials/angular-components/openvidu-toolbar-buttons.md
              - Toolbar Panel Buttons: docs/tutorials/angular-components/openvidu-toolbar-panel-buttons.md
              - Custom Layout: docs/tutorials/angular-components/openvidu-custom-layout.md
              - Custom Stream: docs/tutorials/angular-components/openvidu-custom-stream.md
              - Custom Panels: docs/tutorials/angular-components/openvidu-custom-panels.md
              - Additional Panels: docs/tutorials/angular-components/openvidu-additional-panels.md
              - Custom Chat Panel: docs/tutorials/angular-components/openvidu-custom-chat-panel.md
              - Custom Activities Panel: docs/tutorials/angular-components/openvidu-custom-activities-panel.md
              - Custom Participants Panel: docs/tutorials/angular-components/openvidu-custom-participants-panel.md
              - Custom Participant Panel Item: docs/tutorials/angular-components/openvidu-custom-participant-panel-item.md
              - Custom Participant Panel Item Element: docs/tutorials/angular-components/openvidu-custom-participant-panel-item-element.md
              - Toggle Hand: docs/tutorials/angular-components/openvidu-toggle-hand.md
              - Admin Dashboard: docs/tutorials/angular-components/openvidu-admin-dashboard.md
          - AI Services:
              - docs/tutorials/ai-services/index.md
              - Live Captions: docs/tutorials/ai-services/openvidu-live-captions.md
      - Self-hosting:
          - Deployment types: docs/self-hosting/deployment-types.md
          - Production ready:
              - docs/self-hosting/production-ready/index.md
              - Performant: docs/self-hosting/production-ready/performance.md
              - Scalable: docs/self-hosting/production-ready/scalability.md
              - Fault Tolerant: docs/self-hosting/production-ready/fault-tolerance.md
              - Observable:
                  - docs/self-hosting/production-ready/observability/index.md
                  - OpenVidu Dashboard: docs/self-hosting/production-ready/observability/openvidu-dashboard.md
                  - Grafana Stack: docs/self-hosting/production-ready/observability/grafana-stack.md
          - Local (Development): docs/self-hosting/local.md
          - <span class="openvidu-tag-nav openvidu-community-tag">COMMUNITY</span> Single Node:
              - docs/self-hosting/single-node/index.md
              - On Premises:
                  - Install: docs/self-hosting/single-node/on-premises/install.md
                  - Administration: docs/self-hosting/single-node/on-premises/admin.md
                  - Upgrade: docs/self-hosting/single-node/on-premises/upgrade.md
              - AWS:
                  - Install: docs/self-hosting/single-node/aws/install.md
                  - Administration: docs/self-hosting/single-node/aws/admin.md
                  - Upgrade: docs/self-hosting/single-node/aws/upgrade.md
              - Azure:
                  - Install: docs/self-hosting/single-node/azure/install.md
                  - Administration: docs/self-hosting/single-node/azure/admin.md
                  - Upgrade: docs/self-hosting/single-node/azure/upgrade.md
          - <span class="openvidu-tag-nav openvidu-pro-tag">PRO</span> Single Node:
              - docs/self-hosting/single-node-pro/index.md
              - On Premises:
                  - Install: docs/self-hosting/single-node-pro/on-premises/install.md
                  - Administration: docs/self-hosting/single-node-pro/on-premises/admin.md
                  - Upgrade: docs/self-hosting/single-node-pro/on-premises/upgrade.md
              - AWS:
                  - Install: docs/self-hosting/single-node-pro/aws/install.md
                  - Administration: docs/self-hosting/single-node-pro/aws/admin.md
                  - Upgrade: docs/self-hosting/single-node-pro/aws/upgrade.md
              - Azure:
                  - Install: docs/self-hosting/single-node-pro/azure/install.md
                  - Administration: docs/self-hosting/single-node-pro/azure/admin.md
                  - Upgrade: docs/self-hosting/single-node-pro/azure/upgrade.md
          - <span class="openvidu-tag-nav openvidu-pro-tag">PRO</span> Elastic:
              - docs/self-hosting/elastic/index.md
              - On Premises:
                  - Install: docs/self-hosting/elastic/on-premises/install.md
                  - Administration: docs/self-hosting/elastic/on-premises/admin.md
                  - Upgrade: docs/self-hosting/elastic/on-premises/upgrade.md
              - AWS:
                  - Install: docs/self-hosting/elastic/aws/install.md
                  - Administration: docs/self-hosting/elastic/aws/admin.md
                  - Upgrade: docs/self-hosting/elastic/aws/upgrade.md
              - Azure:
                  - Install: docs/self-hosting/elastic/azure/install.md
                  - Administration: docs/self-hosting/elastic/azure/admin.md
                  - Upgrade: docs/self-hosting/elastic/azure/upgrade.md
          - <span class="openvidu-tag-nav openvidu-pro-tag">PRO</span> High Availability:
              - docs/self-hosting/ha/index.md
              - On Premises:
                  - Install with DNS Load Balancing: docs/self-hosting/ha/on-premises/install-dlb.md
                  - Install with Network Load Balancer: docs/self-hosting/ha/on-premises/install-nlb.md
                  - Administration: docs/self-hosting/ha/on-premises/admin.md
                  - Upgrade: docs/self-hosting/ha/on-premises/upgrade.md
              - AWS:
                  - Install: docs/self-hosting/ha/aws/install.md
                  - Administration: docs/self-hosting/ha/aws/admin.md
                  - Upgrade: docs/self-hosting/ha/aws/upgrade.md
              - Azure:
                  - Install: docs/self-hosting/ha/azure/install.md
                  - Administration: docs/self-hosting/ha/azure/admin.md
                  - Upgrade: docs/self-hosting/ha/azure/upgrade.md
          - Configuration:
              - Changing config: docs/self-hosting/configuration/changing-config.md
              - Config system in depth: docs/self-hosting/configuration/in-depth.md
              - Config reference: docs/self-hosting/configuration/reference.md
          - How To Guides:
              - docs/self-hosting/how-to-guides/index.md
              - Configure external S3: docs/self-hosting/how-to-guides/external-s3.md
              - Force traffic to 443 TLS: docs/self-hosting/how-to-guides/force-443-tls.md
              - Enable webhooks: docs/self-hosting/how-to-guides/enable-webhooks.md
              - Enable and disable modules: docs/self-hosting/how-to-guides/enable-disable-modules.md
              - Deploy and configure with an external proxy: docs/self-hosting/how-to-guides/deploy-with-external-proxy.md
              - Create AWS certificate for HA: docs/self-hosting/how-to-guides/create-configure-AWS-certificate.md
            # - FAQ: docs/self-hosting/faq.md
      - AI Services:
          - Overview: docs/ai/overview.md
          - Live captions: docs/ai/live-captions.md
          - OpenVidu agents:
              - Overview: docs/ai/openvidu-agents/overview.md
              - Speech Processing agent: docs/ai/openvidu-agents/speech-processing-agent.md
              - Agent dispatch: docs/ai/openvidu-agents/agent-dispatch.md
          - Custom agents: docs/ai/custom-agents.md
      - UI Components:
          - Angular Components: docs/ui-components/angular-components.md
          - React Components: docs/ui-components/react-components.md
      - OpenVidu Call:
          - docs/openvidu-call/index.md
          - Docs: docs/openvidu-call/docs.md
      - Releases: docs/releases.md
  # - Blog:
  #     - blog/index.md
  - Support:
      - support.md
  - Pricing:
      - pricing.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  features:
    - content.code.copy
    - content.tabs.link
    - content.code.annotate
    - content.tooltips
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - navigation.footer
    # - navigation.expand
    # - navigation.path
    # - navigation.sections
    - navigation.top
    - navigation.indexes
    # - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    # - header.autohide
    - announce.dismiss
  font:
    text: Tomorrow # Nunito Sans, Rubik, Barlow, Raleway, Open Sans, Tomorrow, IBM Plex Sans
    code: Roboto Mono
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  favicon: assets/images/logo.png
  logo: assets/images/openvidu_globe_bg_transp_cropped.png

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - do-not-include-in-gallery
      auto_caption: false
      caption_position: bottom
      background: none
      shadow: false
  - blog
  - meta

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.snippets:
      url_download: true
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version:
    provider: mike
    default: latest
    alias: true
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/OpenVidu
    - icon: simple/x
      link: https://x.com/openvidu
    - icon: simple/medium
      link: https://openvidu.medium.com/
    - icon: simple/youtube
      link: https://www.youtube.com/@openvidu
  consent:
    title: Cookie consent
    description: >
      This website uses cookies to ensure you get the best experience on our website.
      <a href="/conditions/cookie-policy/" target="_blank">See cookie policy</a>
    cookies:
      analytics:
        name: Google Analytics
        checked: true

extra_css:
  - stylesheets/colors.css
  - stylesheets/extra.css
  - stylesheets/unsemantic-grid.css
  - stylesheets/livekit-tutorials.css
  - stylesheets/amplify.css
  - stylesheets/home.css
  - stylesheets/openvidu-call.css
  - javascripts/openvidu-register/openvidu-register.css

extra_javascript:
  - javascripts/openvidu-register/openvidu-register.js

copyright: >
  2025 &copy; OpenVidu â€“
  <a href="#__consent">Change cookie settings</a>
